local panel = Instance.new("ScreenGui")
panel.Name = "Metaverseal"
panel.Parent = game.Players.LocalPlayer.PlayerGui
panel.IgnoreGuiInset = true
local panelhoilder = Instance.new("Frame")
panelhoilder.Name = "Holder"
panel.DisplayOrder = 69696969699696969696
panelhoilder.Parent = panel
local uilistholder = Instance.new("UIListLayout")
uilistholder.Parent = panelhoilder
uilistholder.HorizontalAlignment = Enum.HorizontalAlignment.Center
uilistholder.VerticalAlignment = Enum.VerticalAlignment.Center
local paneholdertext = Instance.new("TextLabel")
panelhoilder.Size = UDim2.new(1,0,1,0)
panelhoilder.Transparency =1
paneholdertext.BackgroundTransparency = 1
paneholdertext.Size = UDim2.new(0.245, 0,0.051, 0)
paneholdertext.Font = Enum.Font.Jura
paneholdertext.FontFace.Weight = Enum.FontWeight.Bold
paneholdertext.Text = "Metaverseal"
paneholdertext.TextColor3 = Color3.fromRGB(34, 255, 0)
paneholdertext.TextScaled =true
local uipad = Instance.new("UIPadding")
uipad.Parent= panelhoilder
paneholdertext.Parent = panelhoilder
